# Uncomment this line to define a global platform for your project

# 忽略引入库的所有警告
inhibit_all_warnings!

target 'FitCloudKitDemo' do
  platform :ios, '12.0'
  workspace 'FitCloudKitDemo.xcworkspace'
  project 'FitCloudKitDemo.xcodeproj'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for FitCloudKitDemo
  pod 'QuickTraceiOSLogger'
  pod 'YYCategories'
  pod 'Toast'
  pod 'YYModel'

  #############################---拓步Pod---######################################
  # 拓步智能手表 SDK
  pod 'FitCloudKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
  # 拓步能手环固件升级 SDK
  pod 'FitCloudDFUKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
  # 拓步能手表表盘 SDK 适用于 Realtek 芯片
  pod 'FitCloudWFKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
  # 拓步能手表表盘 SDK 适用于 Nordic 芯片
  pod 'FitCloudNWFKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
  pod 'AFNetworking', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'JPImageresizerView'
  pod 'TSDialWidget', git: 'https://github.com/htangsmart/TSDialWidget-iOS.git'
  #拓步-BES
#  pod 'TopStepComKit', git: 'https://github.com/htangsmart/TopStepComKit-IOS.git'
  pod 'TopStepComKit', :path => '../'
  
  #################################################################################
  
  end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
