#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef TOPSTEPAISDK_SWIFT_H
#define TOPSTEPAISDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TopStepAISDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
/// Enumeration for Text-to-Speech error codes
typedef SWIFT_ENUM(NSInteger, TTSErrorCode, open) {
/// Failed to save audio file
  TTSErrorCodeAudioFileSaveFailed = 1001,
/// Failed to convert audio
  TTSErrorCodeAudioConversionFailed = 1002,
/// Invalid URL
  TTSErrorCodeInvalidURL = 1003,
/// Network request failed
  TTSErrorCodeNetworkRequestFailed = 1004,
/// Server error
  TTSErrorCodeServerError = 1005,
/// File not found
  TTSErrorCodeFileNotFound = 1006,
/// Unknown error
  TTSErrorCodeUnknown = 9999,
};

@class NSString;
@protocol LoggableProtocol;

/// TopStepAISDK is an AI-powered SDK that offers a range of advanced features, including Automatic Speech Recognition (ASR), Text-to-Speech (TTS), AI-generated imagery (AIGC), AI-driven question answering (GPT), and AI translation services.
/// important:
/// Make sure to properly initialize the SDK before using its features
SWIFT_CLASS("_TtC12TopStepAISDK9TopStepAI")
@interface TopStepAI : NSObject
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepAI
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkBuild;)
+ (NSString * _Nonnull)sdkBuild SWIFT_WARN_UNUSED_RESULT;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkReleaseDate;)
+ (NSString * _Nonnull)sdkReleaseDate SWIFT_WARN_UNUSED_RESULT;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersionDescription;)
+ (NSString * _Nonnull)sdkVersionDescription SWIFT_WARN_UNUSED_RESULT;
/// Sets a custom log provider for the SDK
/// important:
/// This method should be called before using any logging functionality
/// note:
/// Only one log provider can be active at a time. Setting a new provider replaces the existing one
/// \param loggable An object conforming to LogMate.loggable protocol that will handle logging
///
+ (void)setLogProvider:(id <LoggableProtocol> _Nonnull)loggable;
/// Sets the MAC address for a watch device and initializes related configurations
/// note:
/// If the provided MAC address is the same as the currently registered one,
/// the completion handler will be called immediately with success
/// important:
/// This method must be called before using any watch-related features
/// \param macAddr The MAC address of the watch device in format “XX:XX:XX:XX:XX:XX” (e.g. “00:11:22:33:44:55”)
///
/// \param completion A closure that will be called when the registration process completes
/// <ul>
///   <li>
///     success: A boolean indicating whether the registration was successful
///   </li>
///   <li>
///     error: An optional Error object containing error information if the registration failed
///   </li>
/// </ul>
///
+ (void)setWatchDeviceMacAddr:(NSString * _Nonnull)macAddr completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end

/// An enumeration representing different AI model types available in the TopStep AI SDK.
/// This enum provides a type-safe way to specify which AI model to use for processing.
/// Each case represents a specific AI model with its associated raw integer value.
/// note:
/// This enum is marked with <code>@objc</code> for Objective-C compatibility.
typedef SWIFT_ENUM(NSInteger, TopStepAIModel, open) {
/// Unspecific
  TopStepAIModelUnspecific = 0,
/// Doubao AI Model
  TopStepAIModelDoubao = 1,
/// DeepSeek AI Model
  TopStepAIModelDeepseek = 2,
/// ChatGLM AI Model
  TopStepAIModelChatglm = 3,
/// ERNIE Bot AI Model
  TopStepAIModelErniebot = 4,
/// Qwen AI Model
  TopStepAIModelQwen = 5,
/// Spark AI Model
  TopStepAIModelSpark = 6,
/// Kimi AI Model
  TopStepAIModelKimi = 7,
};


SWIFT_CLASS("_TtC12TopStepAISDK25TopStepAITranslateService")
@interface TopStepAITranslateService : NSObject
/// Returns the shared singleton instance of TopStepAITranslateService
///
/// returns:
/// The shared TopStepAITranslateService instance
+ (TopStepAITranslateService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepAITranslateService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Translates text from one language to another
/// This method initiates a translation request for the provided text. If there’s an ongoing translation task,
/// it will be terminated and replaced with this new request.
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param text The text content to be translated
///
/// \param targetLanguage The desired language for the translation output
///
/// \param sourceLanguage The language of the input text. If nil, auto-detection will be used
///
/// \param completion A closure called when translation completes, providing:
/// <ul>
///   <li>
///     taskId: A unique identifier for this translation request
///   </li>
///   <li>
///     success: Whether the translation was successful
///   </li>
///   <li>
///     translation: The translated text if successful
///   </li>
///   <li>
///     error: Any error that occurred during translation
///   </li>
/// </ul>
///
///
/// returns:
/// A task identifier that can be used to track this translation request
- (NSString * _Nullable)translateWithText:(NSString * _Nonnull)text targetLanguage:(NSString * _Nonnull)targetLanguage sourceLanguage:(NSString * _Nullable)sourceLanguage completion:(void (^ _Nullable)(NSString * _Nullable, BOOL, NSString * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end

@class NSData;
@class AVAudioPCMBuffer;

/// A service class that handles automatic speech recognition (ASR) functionality
/// TopStepASRService is designed as a singleton class to provide centralized speech recognition
/// capabilities throughout the application.
/// Example:
/// \code
/// let asrService = TopStepASRService.shared()
///
/// \endcode
SWIFT_CLASS("_TtC12TopStepAISDK17TopStepASRService")
@interface TopStepASRService : NSObject
/// The shared singleton instance of TopStepASRService
///
/// returns:
/// The shared TopStepASRService instance
+ (TopStepASRService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepASRService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initiates voice recognition and sets up handlers for voice data processing and result callbacks
/// This method configures the voice recognition system by establishing handlers for
/// processing voice input and managing recognition output. It supports both standard voice data
/// and PCM buffer processing. The system will continuously process audio input and provide
/// recognition results through the callback handler.
/// important:
/// You cannot provide both voiceDataAppendHandler and pcmBufferAppendHandler simultaneously.
/// Only one type of handler should be used at a time.
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param languageForSpeechInput The language setting for speech input
/// A string representing the language identifier, if not provided, the system will use the current device’s language setting.
/// <blockquote>
/// Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-Hans</code>
///
/// </blockquote>
/// <ul>
///   <li>
///     Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
///   </li>
///   <li>
///     Part2: Script code (ISO 15924) - Optional four letters specifying the writing system (e.g., “Hans” for Simplified Chinese)
///   </li>
/// </ul>
///
/// \param voiceDataAppendHandler A closure for handling voice data input.
/// Processes audio data in chunks with these required specifications:
/// | Parameter        | Specification                                                      |
/// |—————–|——————————————————————|
/// | SampleRate      | 16000.0f                                                          |
/// | FormatID        | LinearPCM                                                         |
/// | FormatFlags     | kLinearPCMFormatFlagIsSignedInteger, kLinearPCMFormatFlagIsPacked|
/// | FramesPerPacket | 1                                                                  |
/// | ChannelsPerFrame| 1                                                                  |
/// | BitsPerChannel  | 16                                                                |
///
/// \param pcmBufferAppendHandler A closure for handling PCM buffer input.
/// Processes PCM buffer with these required specifications:
/// | Parameter        | Specification                                                      |
/// |—————–|——————————————————————|
/// | SampleRate      | 16000.0f                                                          |
/// | FormatID        | LinearPCM                                                         |
/// | FormatFlags     | kLinearPCMFormatFlagIsSignedInteger, kLinearPCMFormatFlagIsPacked|
/// | FramesPerPacket | 1                                                                  |
/// | ChannelsPerFrame| 1                                                                  |
/// | BitsPerChannel  | 16                                                                |
///
/// \param onResult A callback closure for recognition results.
///
/// \a onResult parameters:
/// <ul>
/// <li>
/// taskId: The unique identifier for the recognition session
/// </li>
/// <li>
/// isFinal: Indicates if this is the final recognition result
/// </li>
/// <li>
/// text: The recognized text output, if available
/// </li>
/// <li>
/// error: Any error that occurred during recognition recognition
/// </li>
/// </ul>
///
///
///
/// returns:
/// A unique task identifier string for the recognition session. This ID can be used to track or manage the recognition task.
- (NSString * _Nullable)createVoiceRecognizeTaskWithLanguageForSpeechInput:(NSString * _Nullable)languageForSpeechInput voiceDataAppendHandler:(void (^ _Nullable)(void (^ _Nullable)(NSData * _Nonnull)))voiceDataAppendHandler pcmBufferAppendHandler:(void (^ _Nullable)(void (^ _Nullable)(AVAudioPCMBuffer * _Nonnull)))pcmBufferAppendHandler onResult:(void (^ _Nullable)(NSString * _Nullable, BOOL, NSString * _Nullable, NSError * _Nullable))onResult SWIFT_WARN_UNUSED_RESULT;
/// Finishes the current speech recognition session
/// This method terminates the ongoing speech recognition process.
/// note:
/// This method should be called when you want to stop the speech recognition process
/// and get the final results.
- (void)finish;
@end


/// A model class representing an AI algorithm with its properties.
SWIFT_CLASS("_TtC12TopStepAISDK25TopStepAigcAlgorithmModel")
@interface TopStepAigcAlgorithmModel : NSObject
/// The name of the algorithm.
/// note:
/// This property identifies the algorithm by its name.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The style code of the algorithm.
/// note:
/// This code represents the unique identifier for the algorithm’s style.
@property (nonatomic, readonly, copy) NSString * _Nonnull styleCode;
/// The URL string pointing to the algorithm’s icon.
/// note:
/// This optional property can be nil if no icon is available.
@property (nonatomic, readonly, copy) NSString * _Nullable iconUrl;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepAigcAlgorithmModel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;

/// A service class that provides AI-generated content functionality.
/// TopStepAigcService follows the singleton pattern to ensure only one instance exists throughout the app lifecycle.
/// Use this class to access AI generation features and capabilities.
/// Example:
/// \code
/// let aigcService = TopStepAigcService.shared()
///
/// \endcode
SWIFT_CLASS("_TtC12TopStepAISDK18TopStepAigcService")
@interface TopStepAigcService : NSObject
/// Returns the shared singleton instance of TopStepAigcService
///
/// returns:
/// The shared TopStepAigcService instance
+ (TopStepAigcService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepAigcService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Returns supported aigc styles
/// <blockquote>
/// Warning: When it is nil, you may invoke the <code>fetchAigcStyles(completion:)</code> method to update.
///
/// </blockquote>
///
/// returns:
///
/// supported aigc styles
@property (nonatomic, readonly, copy) NSArray<TopStepAigcAlgorithmModel *> * _Nullable aigcStyles;
/// Returns the max generate count
///
/// returns:
///
/// the max generate count
@property (nonatomic, readonly) NSInteger maxGenerateCount;
/// fetch aigc styles
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param completion The completion handler
/// <ul>
///   <li>
///     success: A boolean value indicating whether the fetch operation was successful
///   </li>
///   <li>
///     aigcStyles: An array of MLTCloudAigcAlgorithmModel objects representing the available AIGC styles, or nil if the fetch failed
///   </li>
///   <li>
///     error: An error object that indicates why the fetch failed, or nil if the fetch was successful
///   </li>
/// </ul>
///
- (void)fetchAigcStylesWithCompletion:(void (^ _Nullable)(BOOL, NSArray<TopStepAigcAlgorithmModel *> * _Nullable, NSError * _Nullable))completion;
/// Generate photos based on the given prompt and style
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param prompt The text description used to generate the images
///
/// \param style The algorithm style identifier to apply for image generation
///
/// \param imageCount The number of images to generate (maximum 4)
///
/// \param completion The completion handler
/// <ul>
///   <li>
///     taskId: A unique task identifier string for the aigc session. This ID can be used to track or manage the task.
///   </li>
///   <li>
///     success: A boolean value indicating whether the generation was successful
///   </li>
///   <li>
///     images: An array of generated UIImage objects, or nil if generation failed
///   </li>
///   <li>
///     error: An error object that indicates why the generation failed, or nil if successful
///   </li>
/// </ul>
///
///
/// returns:
/// A unique task identifier string for the aigc session. This ID can be used to track or manage the task.
- (NSString * _Nullable)generateWithPrompt:(NSString * _Nonnull)prompt style:(NSString * _Nonnull)style imageCount:(NSInteger)imageCount completion:(void (^ _Nullable)(NSString * _Nullable, BOOL, NSArray<UIImage *> * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end

@class TopStepWatchDeviceModel;

SWIFT_CLASS("_TtC12TopStepAISDK17TopStepGPTService")
@interface TopStepGPTService : NSObject
/// Returns the shared singleton instance of TopStepGPTService
///
/// returns:
/// The shared TopStepGPTService instance
+ (TopStepGPTService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepGPTService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Sends a question to the AI service and handles the response through callbacks
/// This method sends a question to either the domestic or international GPT service based on configuration.
/// It supports streaming responses and provides various callbacks to handle the answer process.
/// note:
/// If a question is already being processed, the previous query will be terminated
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param question The question text to be sent to the AI service
///
/// \param fromDevice Optional TopStepWatchDeviceModel associated with the question
///
/// \param usingSpecifiedModel The AI model to use for processing the question (defaults to .unspecific)
///
/// \param onStartAnswering Callback triggered when the service starts processing the question
///
/// \param onAnswer Callback triggered for each response chunk during streaming
///
/// \param onFinishAnswering Callback triggered when the service completes processing the question
///
/// \param onError Callback triggered if an error occurs during processing
///
///
/// returns:
/// A unique question identifier if successful, nil otherwise
- (NSString * _Nullable)sendWithQuestion:(NSString * _Nonnull)question fromDevice:(TopStepWatchDeviceModel * _Nullable)fromDevice usingSpecifiedModel:(enum TopStepAIModel)usingSpecifiedModel onStartAnswering:(void (^ _Nullable)(NSString * _Nullable))onStartAnswering onAnswer:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nullable, NSString * _Nullable, BOOL))onAnswer onFinishAnswering:(void (^ _Nullable)(NSString * _Nonnull))onFinishAnswering onError:(void (^ _Nullable)(NSString * _Nonnull, NSError * _Nonnull))onError SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12TopStepAISDK17TopStepTTSService")
@interface TopStepTTSService : NSObject
/// Returns the shared singleton instance of TopStepTTSService
///
/// returns:
/// The shared TopStepTTSService instance
+ (TopStepTTSService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepTTSService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Synthesizes text into speech
/// note:
/// This method initiates a text-to-speech synthesis request.
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param text The text to be synthesized
///
/// \param completion A closure called when synthesis completes, providing:
/// <ul>
///   <li>
///     taskId: A unique identifier for this synthesis request
///   </li>
///   <li>
///     success: Whether the synthesis was successful
///   </li>
///   <li>
///     audioPath: The local path to the synthesized audio file
///   </li>
///   <li>
///     error: Any error that occurred during synthesis
///   </li>
/// </ul>
///
///
/// returns:
/// The task identifier for the synthesis request
- (NSString * _Nullable)synthesizeTextWithText:(NSString * _Nonnull)text completion:(void (^ _Nullable)(NSString * _Nullable, BOOL, NSString * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;

/// A model class representing a TopStep watch device.
/// This class encapsulates the essential information about a TopStep watch device,
/// including its name, MAC address, model identifier, and project number.
/// <h2>Overview</h2>
/// <code>TopStepWatchDeviceModel</code> provides a structured way to manage and access
/// device-related information. It includes properties for device identification
/// and categorization.
/// <h2>Topics</h2>
/// <h3>Creating a Device Model</h3>
/// <ul>
///   <li>
///     <code>init(name:macAddress:model:projectNumber:)</code>
///   </li>
/// </ul>
/// <h3>Device Properties</h3>
/// <ul>
///   <li>
///     <code>name</code>
///   </li>
///   <li>
///     <code>macAddress</code>
///   </li>
///   <li>
///     <code>model</code>
///   </li>
///   <li>
///     <code>projectNumber</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12TopStepAISDK23TopStepWatchDeviceModel")
@interface TopStepWatchDeviceModel : NSObject <NSCoding, NSCopying>
/// The name of the device.
/// This property stores the display name or identifier of the device.
@property (nonatomic, copy) NSString * _Nonnull name;
/// The MAC address of the device.
/// A unique identifier representing the device’s network hardware address.
/// note:
/// Can be nil if the device’s MAC address is not available.
@property (nonatomic, copy) NSString * _Nullable macAddress;
/// The model identifier of the device.
/// Represents the specific model or version of the device.
/// note:
/// Can be nil if the model information is not available.
@property (nonatomic, copy) NSString * _Nullable model;
/// The project number associated with the device.
/// A unique identifier used for project tracking or categorization.
/// note:
/// Can be nil if no project number is assigned.
@property (nonatomic, copy) NSString * _Nullable projectNumber;
/// Initializes a new instance of the <code>TopStepWatchDeviceModel</code> class.
/// \param name The name of the device.
///
/// \param macAddress The MAC address of the device.
///
/// \param model The model identifier of the device.
///
/// \param projectNumber The project number associated with the device.
///
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name macAddress:(NSString * _Nullable)macAddress model:(NSString * _Nullable)model projectNumber:(NSString * _Nullable)projectNumber OBJC_DESIGNATED_INITIALIZER;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of TopStepWatchDeviceModel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Decode object from decoder
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Encode object to encoder
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
/// Create and return a copy of the receiver
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


/// Auto detect (only available for ‘from’ parameter)
SWIFT_CLASS("_TtC12TopStepAISDK18TranslateLanguages")
@interface TranslateLanguages : NSObject
/// Auto detect (only available for ‘from’ parameter)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=auto) NSString * _Nonnull auto_;)
+ (NSString * _Nonnull)auto SWIFT_WARN_UNUSED_RESULT;
/// Chinese (Simplified)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull ch;)
+ (NSString * _Nonnull)ch SWIFT_WARN_UNUSED_RESULT;
/// Chinese (Traditional)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull cht;)
+ (NSString * _Nonnull)cht SWIFT_WARN_UNUSED_RESULT;
/// English
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull en;)
+ (NSString * _Nonnull)en SWIFT_WARN_UNUSED_RESULT;
/// Cantonese
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull yue;)
+ (NSString * _Nonnull)yue SWIFT_WARN_UNUSED_RESULT;
/// Classical Chinese
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull wyw;)
+ (NSString * _Nonnull)wyw SWIFT_WARN_UNUSED_RESULT;
/// Japanese
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull jp;)
+ (NSString * _Nonnull)jp SWIFT_WARN_UNUSED_RESULT;
/// Korean
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull kor;)
+ (NSString * _Nonnull)kor SWIFT_WARN_UNUSED_RESULT;
/// French
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull fra;)
+ (NSString * _Nonnull)fra SWIFT_WARN_UNUSED_RESULT;
/// Spanish
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull spa;)
+ (NSString * _Nonnull)spa SWIFT_WARN_UNUSED_RESULT;
/// Thai
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull th;)
+ (NSString * _Nonnull)th SWIFT_WARN_UNUSED_RESULT;
/// Arabic
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull ara;)
+ (NSString * _Nonnull)ara SWIFT_WARN_UNUSED_RESULT;
/// Russian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull ru;)
+ (NSString * _Nonnull)ru SWIFT_WARN_UNUSED_RESULT;
/// Portuguese
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull pt;)
+ (NSString * _Nonnull)pt SWIFT_WARN_UNUSED_RESULT;
/// German
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull de;)
+ (NSString * _Nonnull)de SWIFT_WARN_UNUSED_RESULT;
/// Italian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull it;)
+ (NSString * _Nonnull)it SWIFT_WARN_UNUSED_RESULT;
/// Greek
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull el;)
+ (NSString * _Nonnull)el SWIFT_WARN_UNUSED_RESULT;
/// Dutch
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull nl;)
+ (NSString * _Nonnull)nl SWIFT_WARN_UNUSED_RESULT;
/// Polish
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull pl;)
+ (NSString * _Nonnull)pl SWIFT_WARN_UNUSED_RESULT;
/// Bulgarian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull bul;)
+ (NSString * _Nonnull)bul SWIFT_WARN_UNUSED_RESULT;
/// Estonian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull est;)
+ (NSString * _Nonnull)est SWIFT_WARN_UNUSED_RESULT;
/// Danish
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull dan;)
+ (NSString * _Nonnull)dan SWIFT_WARN_UNUSED_RESULT;
/// Finnish
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull fin;)
+ (NSString * _Nonnull)fin SWIFT_WARN_UNUSED_RESULT;
/// Czech
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull cs;)
+ (NSString * _Nonnull)cs SWIFT_WARN_UNUSED_RESULT;
/// Romanian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull rom;)
+ (NSString * _Nonnull)rom SWIFT_WARN_UNUSED_RESULT;
/// Slovenian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull slo;)
+ (NSString * _Nonnull)slo SWIFT_WARN_UNUSED_RESULT;
/// Swedish
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull swe;)
+ (NSString * _Nonnull)swe SWIFT_WARN_UNUSED_RESULT;
/// Hungarian
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull hu;)
+ (NSString * _Nonnull)hu SWIFT_WARN_UNUSED_RESULT;
/// Vietnamese
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull vie;)
+ (NSString * _Nonnull)vie SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
